#!/usr/bin/env python
"""
Minimal Example
===============
Generating a square wordcloud from the Star Wars: A New Hope using default arguments.

All code generated by writers of word_cloud module (https://github.com/amueller/word_cloud)
Used for educational purposes
"""

from os import path
from wordcloud import WordCloud

d = path.dirname(__file__)

# Read the whole text.
text = open(path.join(d, 'a_new_hope.txt')).read()

# Generate a word cloud image
wordcloud = WordCloud().generate(text)

# Display the generated image:
# the matplotlib way:
import matplotlib.pyplot as plt
#plt.imshow(wordcloud)
#plt.axis("off")

# lower max_font_size
wordcloud = WordCloud(max_font_size=40).generate(text)
plt.figure()
plt.imshow(wordcloud)
plt.axis("off")
plt.show()